[package]
name = "togatog_ai"
version = "2.1.0"
authors = ["togatoga <togasakitogatoga@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33"
csv = "1"
serde_derive = "1.0.90"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
